version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - ./backend/yarn.lock:/app/yarn.lock
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5533:5533"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/yarn.lock:/app/yarn.lock
      - ./frontend/webpack.config.js:/app/webpack.config.js
