services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "3333"
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    plan: free

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "5533"
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    plan: free
